name: My Git Workflow

on:
  workflow_dispatch:

  pull_request:
    branches:
      - master

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Pull Request Body
        run: |
          # Use a script (e.g., Bash) to parse the pull request body and extract the required data
          PR_BODY=$(curl -sSL "${{ github.event.pull_request.url }}" | jq -r '.body')

          # Extract the relevant data from PR_BODY using regular expressions and set it as environment variables
          export MY_VAR_1=$(echo "${PR_BODY}" | grep -o 'VAR_1=.*' | cut -d= -f2)
          export MY_VAR_2=$(echo "${PR_BODY}" | grep -o 'VAR_2=.*' | cut -d= -f2)

      - name: Display Variable 1
        run: echo "Variable 1: ${{ env.MY_VAR_1 }}"
      - name: Display Variable 2
        run: echo "Variable 2: ${{ env.MY_VAR_2 }}"
